routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

//AUTH VIEWS
Route::group(['middleware' => 'auth'], function () {

    //SEARCH ROUTES
    Route::get('coupon/search', 'CouponController@search')->name('coupon.search');
    Route::get('customers/search', 'CustomerController@search')->name('customers.search');
    Route::get('customers/search-from-home', 'CustomerController@searchFromHome')->name('customers.search-from-home');

	Route::resource('user', 'UserController');
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::post('crop-image', ['as'=>'upload-image','uses'=>'UserController@imageCrop']);
    Route::post('crop-image-coupon', ['as'=>'upload-image-coupon','uses'=>'CouponController@imageCrop']);
	Route::resource('coupon', 'CouponController');
	Route::resource('category', 'CouponCategoryController', ['except' => ['show', 'search']]);
	Route::resource('category', 'CouponCategoryController', ['except' => ['show', 'search']]);
    Route::resource('customers', 'CustomerController');
    Route::resource('operations', 'OperationController', ['except' => ['show, create, destroy']]);
    Route::resource('card', 'CardController', ['except' => ['show', 'create', 'edit']]);
    Route::resource('movement', 'MovementController', ['except' => ['show', 'create', 'edit']]);

    Route::get('customers/{customer}/cards', 'CustomerController@cards')->name('customers.cards');
    Route::put('customers/{customer}/password', 'CustomerController@password')->name('customers.password');

    //PRIZE VALIDATION
    Route::put('validate/{user}/{prize}', 'HomeController@validatePrize')->name('validate-prize');

    //FRONTEND ROUTES
    Route::get('premi/{slug}', 'FrontendController@showCoupon')->name('frontend.show-coupon');
    Route::post('{coupon}/richiesta-premio', 'FrontendController@requestPrize')->name('frontend.request-prize');
    Route::get('movimenti', 'FrontendController@allMovements')->name('frontend.movements');
    Route::get('richiesta-premio/{slug}', 'FrontendController@prizeStatus')->name('frontend.prize-status');

});

Route::get('links/{slug}', 'GuestController@showCoupon')->name('guest.show-coupon');

app/Coupon.php
<?php

namespace App;

use App\User;
use App\CouponCategory;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class Coupon extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'slug', 'description', 'location', 'deadline', 'value', 'availability', 'category_id', 'img'
    ];

    /**
     * Coupon users relationship.
     */
    public function Users() {
        return $this->belongsToMany(User::class)->withPivot('accepted');
    }

    /**
     * Coupon category relationship.
     */
    public function Category(){
        return $this->belongsTo(CouponCategory::class);
    }

}

app/Http/Controllers/CouponController.php
<?php

namespace App\Http\Controllers;

use App\Coupon;
use App\CouponCategory;
use Illuminate\Support\Facades\File;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Http\Request;
use App\Http\Requests\CouponRequest;
use App\Http\Requests\CouponSearchRequest;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;
use Carbon\Carbon;

class CouponController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param \App\Coupon $model
     * @param Request $request
     * @return \Illuminate\View\View
     * @throws \Throwable
     */
    public function index(Coupon $model, Request $request)
    {
        $categories = CouponCategory::all();

        if ($request->ajax()) {
            return response()->json(['titolo'=>null,'tipo'=>null,'messaggio'=>null,'risultato'=>view('coupon.content', ['coupons' => $model->paginate(6), 'categories' => $categories])->render()]);
        }

        return view('coupon.index', ['coupons' => $model->paginate(6), 'categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $categories = CouponCategory::all();

        return view('coupon.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\CouponRequest  $request
     * @param  \App\Coupon  $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CouponRequest $request, Coupon $model)
    {
        $slug = Str::slug($request->title, '-');

        $deadline = Carbon::createFromFormat('d/m/Y', $request->deadline)->format('Y-m-d');
    

        if($request->img !== 'coupon_img.png'){
            $image = $request->img;
            $name = time().'.png';
            $path = 'public/images/coupons/' . $name;

            list($type, $image) = explode(';', $image);
            list(, $image)      = explode(',', $image);
            $image = base64_decode($image);

            $img = Image::make($image);

            $img->stream();

            Storage::disk('local')->put($path, $img);

            $model->create($request->merge(['slug' => $slug, 'img' => $name, 'deadline' => $deadline])->all());

        } else {
            $model->create($request->merge(['slug' => $slug, 'deadline' => $deadline])->all());
        }

        return redirect()->route('coupon.index')->withStatus(__('Coupon creato con successo.'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Coupon  $coupon
     * @return \Illuminate\Http\Response
     */
    public function show(Coupon $coupon)
    {
        if($coupon->Category){
           $category_name = $coupon->category->name; 
        } else {
            $category_name = 'Uncategorized';
        }
        return view('coupon.show', compact('coupon', 'category_name'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Coupon  $coupon
     * @return \Illuminate\View\View
     */
    public function edit(Coupon $coupon)
    {
        $categories = CouponCategory::all();

        return view('coupon.edit', compact('coupon', 'categories'));
    }


    /**
     * Update the specified coupon in storage.
     *
     * @param Request $request
     * @param Coupon $coupon
     * @return mixed
     */
    public function update(Request $request, Coupon $coupon)
    {
        if($request->img != $coupon->img && $request->img != 'coupon_img.png'){

            Storage::delete('public/images/coupons/'.$coupon->img);

            $image = $request->img;
            $name = time().'.png';
            $path = 'public/images/coupons/' . $name;

            list($type, $image) = explode(';', $image);
            list(, $image)      = explode(',', $image);
            $image = base64_decode($image);

            $img = Image::make($image);

            $img->stream();

            Storage::disk('local')->put($path, $img);

            $coupon->update([
                'img' => $name
            ]);

            $coupon->save();
        };

        $deadline = Carbon::createFromFormat('d/m/Y', $request->deadline)->format('Y-m-d');

        $coupon->update([
            'title' => $request->title,
            'description' => $request->description,
            'location' => $request->location,
            'deadline' => $deadline,
            'value' => $request->value,
            'availability' => $request->availability,
            'category_id' => $request->category_id
        ]);

        $coupon->save();

        return redirect()->route('coupon.index')->withStatus(__('Coupon aggiornato con successo.'));
    }

    /**
     * Remove the specified coupon from storage.
     *
     * @param  \App\Coupon  $coupon
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Coupon $coupon)
    {
        if($coupon->img != 'coupon_img.png') {
            Storage::delete('public/images/coupons/'.$coupon->img);
        }
        $coupon->delete();

        return redirect()->route('coupon.index')->withStatus(__('Premio eliminato con successo!'));
    }

    /**
     * Search method.
     */
    public function search(Request $request) {

        if($request->category){
            $categories = array();
            foreach($request->category as $category){
                    $categories[] = $category;
            }
        }

        if($request->location) {
            $locations = array();
            foreach($request->location as $location){
                $locations[] = $location;
            }
        }
        

        if($request->category && $request->location) {
            $coupons = Coupon::WhereIn('category_id', $categories, 'and')->WhereIn('location', $locations, 'and')->orderBy('location')->paginate(5);
        }
        elseif($request->location) {
            $coupons = Coupon::WhereIn('location', $locations)->orderBy('location')->paginate(5);
        }
        elseif($request->category) {
            $coupons = Coupon::WhereIn('category_id', $categories)->orderBy('category_id')->paginate(5);
        }
        else {
            $coupons = Coupon::Where('title', 'LIKE', '%'.$request->search.'%')
            ->orWhere('description', 'LIKE', '%'.$request->search.'%')
            ->paginate(5);
        }
        $categories = CouponCategory::all();
        return response()->json(['titolo'=>null,'tipo'=>null,'messaggio'=>null,'risultato'=>view('coupon.content', compact('coupons','categories'))->render()]);
    }

    /**
     * Image crop method
     */

    public function imageCrop(Request $request){
        $image_file = $request->image;
        return response()->json(['status'=>true, 'img' => $image_file]);
      }


      public function convalidaPremio(Coupon $coupon) {
        $coupon->update([
            'accepted' => 'true'
        ]);

        $coupon->save();
          return response()->json(['titolo'=>null,'tipo'=>null,'messaggio'=>null,'risultato'=>view('coupon.content', compact('coupons','categories'))->render()]);
      }

}

resources/views/coupon/categories/create.blade.php
@extends('layouts.app', ['activePage' => 'coupon_categories', 'title' => __('Add new category'),])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('category.store') }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('post')

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Add new Category') }}</h4>
                <p class="card-category"></p>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('category.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Name') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Name') }}" value="{{ old('name') }}" required="true" aria-required="true"/>
                      @if ($errors->has('name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Icon') }} (Material Icons)</label>
                  <div class="col-sm-7">
                    <select class="selectpicker" name="icon" id="input-icon" data-style="btn btn-primary btn-round" data-size="7">
                      @foreach ($icons as $icon)
                          <option class="material-icons" value="{{$icon}}">{{$icon}}</option>
                      @endforeach
                    </select>
                    @if ($errors->has('icon'))
                        <span id="icon-error" class="error text-danger" for="input-icon">{{ $errors->first('icon') }}</span>
                      @endif
                  </div>
                </div>
              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Add Category') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/coupon/categories/edit.blade.php
@extends('layouts.app', ['activePage' => 'coupon_categories', 'title' => __('Edit Category')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('category.update', $category) }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('put')

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Edit Category') }}</h4>
                <p class="card-category"></p>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('category.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Name') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Name') }}" value="{{ old('name', $category->name) }}" required="true" aria-required="true"/>
                      @if ($errors->has('name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/coupon/categories/index.blade.php
@extends('layouts.app', ['activePage' => 'coupon_categories', 'title' => __('Categories Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">{{ __('Coupon Categories') }}</h4>
                <p class="card-category"> {{ __('Here you can manage coupon categories') }}</p>
              </div>
              <div class="card-body">
                @if (session('status'))
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <i class="material-icons">close</i>
                        </button>
                        <span>{{ session('status') }}</span>
                      </div>
                    </div>
                  </div>
                @endif
                <div class="row">
                  <div class="col-12 text-right">
                    <a href="{{ route('category.create') }}" class="btn btn-sm btn-primary">{{ __('Add category') }}</a>
                  </div>
                </div>
                <div class="table-responsive">
                  <table class="table">
                    <thead class=" text-primary">
                      <th>
                        {{ __('Icon') }}
                      </th>
                      <th>
                        {{ __('Name') }}
                      </th>
                      <th>
                          {{ __('Actions') }}
                      </th>
                    </thead>
                    <tbody>
                      @foreach($categories as $category)
                        <tr>
                          <td>
                            <i class="material-icons" style="color: #a9afbb;">{{ $category->icon }}</i>
                          </td>
                          <td>
                            {{ $category->name }}
                          </td>
                          <td class="td-actions">
                              <form action="{{ route('category.destroy', $category) }}" method="post">
                                  @csrf
                                  @method('delete')
                                  <a rel="tooltip" class="btn btn-success btn-link" href="{{ route('category.edit', $category) }}" data-original-title="" title="">
                                    <i class="material-icons">edit</i>
                                    <div class="ripple-container"></div>
                                  </a>
                                  <button type="button" class="btn btn-danger btn-link" data-original-title="" title="" onclick="confirm('{{ __("Are you sure you want to delete this category?") }}') ? this.parentElement.submit() : ''">
                                      <i class="material-icons">close</i>
                                      <div class="ripple-container"></div>
                                  </button>
                              </form>
                          </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
@endsection