routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

//AUTH VIEWS
Route::group(['middleware' => 'auth'], function () {

    //SEARCH ROUTES
    Route::get('coupon/search', 'CouponController@search')->name('coupon.search');
    Route::get('customers/search', 'CustomerController@search')->name('customers.search');
    Route::get('customers/search-from-home', 'CustomerController@searchFromHome')->name('customers.search-from-home');

	Route::resource('user', 'UserController');
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::post('crop-image', ['as'=>'upload-image','uses'=>'UserController@imageCrop']);
    Route::post('crop-image-coupon', ['as'=>'upload-image-coupon','uses'=>'CouponController@imageCrop']);
	Route::resource('coupon', 'CouponController');
	Route::resource('category', 'CouponCategoryController', ['except' => ['show', 'search']]);
	Route::resource('category', 'CouponCategoryController', ['except' => ['show', 'search']]);
    Route::resource('customers', 'CustomerController');
    Route::resource('operations', 'OperationController', ['except' => ['show, create, destroy']]);
    Route::resource('card', 'CardController', ['except' => ['show', 'create', 'edit']]);
    Route::resource('movement', 'MovementController', ['except' => ['show', 'create', 'edit']]);

    Route::get('customers/{customer}/cards', 'CustomerController@cards')->name('customers.cards');
    Route::put('customers/{customer}/password', 'CustomerController@password')->name('customers.password');

    //PRIZE VALIDATION
    Route::put('validate/{user}/{prize}', 'HomeController@validatePrize')->name('validate-prize');

    //FRONTEND ROUTES
    Route::get('premi/{slug}', 'FrontendController@showCoupon')->name('frontend.show-coupon');
    Route::post('{coupon}/richiesta-premio', 'FrontendController@requestPrize')->name('frontend.request-prize');
    Route::get('movimenti', 'FrontendController@allMovements')->name('frontend.movements');
    Route::get('richiesta-premio/{slug}', 'FrontendController@prizeStatus')->name('frontend.prize-status');

});

Route::get('links/{slug}', 'GuestController@showCoupon')->name('guest.show-coupon');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'surname', 'city', 'gender', 'phone', 'birthday', 'company', 'job', 'email', 'username', 'password', 'newsletter', 'avatar', 'admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    /**
     * User's coupons relationship.
     */
    public function Coupons() {
        return $this->belongsToMany(Coupon::class)->withTimestamps()->withPivot('accepted');
    }

    /**
     * User's coupon pivot obj.
     */
    public function CouponPivot($id) {
        foreach ($this->coupons as $coupon) {
            if($coupon->id === $id) {
                return $coupon->pivot;
            }
        }
    }
    
    /**
     * User's card relationship.
     */
    public function Cards() {
        return $this->hasMany(Card::class);
    }

    /**
     * User's movements relationship.
     */
    public function Movements() {
        return $this->hasMany(Movement::class);
    }

    /**
     * Customer's card movements.
     */
    public function CustomerMovements() {
        return $this->hasManyThrough(Movement::class, Card::class);
    }


    /**
     * Checks if User is Admin.
     */

    public function isAdmin() {
        return $this->admin ? 1 : 0;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CustomerPasswordRequest;
use App\User;
use App\Http\Requests\UserRequest;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class UserController extends Controller
{
    /**
     * Display a listing of the users
     *
     * @param  \App\User  $model
     * @return \Illuminate\View\View
     */
    public function index(User $model)
    {
        return view('users.index', ['users' => $model->where('admin', 1)->orderBy('name', 'desc')->paginate(15)]);
    }

    /**
     * Show the form for creating a new user
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(UserRequest $request, User $model)
    {
        $model->create($request->merge(['password' => Hash::make($request->get('password')), 'admin' => 1])->all());
        
        return redirect()->route('user.index')->withStatus(__('Nuovo utente creato con successo!'));
    }

    /**
     * Show the form for editing the specified user
     *
     * @param  \App\User  $user
     * @return \Illuminate\View\View
     */
    public function edit(User $user)
    {
        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UserRequest $request, User  $user)
    {
        $user->update(
            $request->merge(['password' => Hash::make($request->get('password'))])
                ->except([$request->get('password') ? '' : 'password']
        ));

        return redirect()->route('user.index')->withStatus(__('User successfully updated.'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show(User $user)
    {
        return response()->json(['titolo'=>null,'tipo'=>'modal','messaggio'=>null,'risultato'=>view('users.show', compact('user'))->render()]);
    }

    /**
     * Remove the specified user from storage
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(User  $user)
    {
        if($user->avatar != '') {
            Storage::delete($user->avatar);
        }
        $user->delete();

        return redirect()->route('user.index')->withStatus(__('User successfully deleted.'));
    }

    /**
     * Image crop method
     */

    public function imageCrop(Request $request){
        
        $image = $request->image;
        $name = time().'.'. $request->extension;
        $path = 'public/images/users/' . $name;

        list($type, $image) = explode(';', $image);
        list(, $image)      = explode(',', $image);
        $image = base64_decode($image);

        $img = Image::make($image);

        $img->stream();
        
        Storage::disk('local')->put($path, $img);

        $user = auth()->user();
        $user->update([
            'avatar' => $name
        ]);

        $user->save();
            

        return response()->json(['status' => true, 'img' => $user->avatar]);
      }
}

resources/views/users/create.blade.php
@extends('layouts.app', ['activePage' => 'user-management', 'title' => __('Aggiungi Utente')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('user.store') }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('post')

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Aggiungi Utente') }}</h4>
                <p class="card-category"></p>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('user.index') }}" class="btn btn-sm btn-primary">{{ __('Torna alla lista') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Nome') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Inserisci nome') }}" value="{{ old('name') }}" required="true" aria-required="true"/>
                      @if ($errors->has('name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Cognome') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('surname') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('surname') ? ' is-invalid' : '' }}" name="surname" id="input-surname" type="text" placeholder="{{ __('Inserisci cognome') }}" value="{{ old('surname') }}" required />
                      @if ($errors->has('surname'))
                        <span id="surname-error" class="error text-danger" for="input-surname">{{ $errors->first('surname') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Email') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" id="input-email" type="email" placeholder="{{ __('Inserisci email') }}" value="{{ old('email') }}" />
                      @if ($errors->has('email'))
                        <span id="email-error" class="error text-danger" for="input-email">{{ $errors->first('email') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Hotel') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('company') ? ' has-danger' : '' }}">
                      <select name="company" class="selectpicker"
                              data-style="btn btn-primary btn-round" data-size="7">
                        <option value="Hotel Promenade">Hotel Promenade</option>
                        <option value="Hotel Villa Medici">Hotel Villa Medici</option>
                      </select>
                      @if ($errors->has('company'))
                        <span id="company-error" class="error text-danger" for="input-company">{{ $errors->first('company') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Username') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('username') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('username') ? ' is-invalid' : '' }}" name="username" id="input-username" type="text" placeholder="{{ __('Inserisci uno username') }}" value="{{ old('username') }}" required />
                      @if ($errors->has('username'))
                        <span id="username-error" class="error text-danger" for="input-surname">{{ $errors->first('username') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label" for="input-password">{{ __(' Password') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" input type="password" name="password" id="input-password" placeholder="{{ __('Inserisci password') }}" value="" required />
                      @if ($errors->has('password'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('password') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label" for="input-password-confirmation">{{ __('Conferma Password') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group">
                      <input class="form-control" name="password_confirmation" id="input-password-confirmation" type="password" placeholder="{{ __('Conferma Password') }}" value="" required />
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Crea utente') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app', ['activePage' => 'user-management', 'title' => __('Modifica Utente')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('user.update', $user) }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('PUT')

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Modifica Utente') }}</h4>
                <p class="card-category"></p>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                    <a href="{{ route('user.index') }}" class="btn btn-sm btn-primary">{{ __('Torna alla lista') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Nome') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="input-name" type="text" placeholder="{{ __('Inserisci nome') }}" value="{{ $user->name }}" required="true" aria-required="true"/>
                      @if ($errors->has('name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Cognome') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('surname') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('surname') ? ' is-invalid' : '' }}" name="surname" id="input-surname" type="text" placeholder="{{ __('Inserisci cognome') }}" value="{{ $user->surname }}" required />
                      @if ($errors->has('surname'))
                        <span id="surname-error" class="error text-danger" for="input-surname">{{ $errors->first('surname') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Email') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" id="input-email" type="email" placeholder="{{ __('Inserisci email') }}" value="{{ $user->email }}" />
                      @if ($errors->has('email'))
                        <span id="email-error" class="error text-danger" for="input-email">{{ $errors->first('email') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Username') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('username') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('username') ? ' is-invalid' : '' }}" name="username" id="input-username" type="text" placeholder="{{ __('Inserisci uno username') }}" value="{{ $user->username }}" required />
                      @if ($errors->has('username'))
                        <span id="username-error" class="error text-danger" for="input-surname">{{ $errors->first('username') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Hotel') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('company') ? ' has-danger' : '' }}">
                      <select name="company" class="selectpicker"
                              data-style="btn btn-primary btn-round" data-size="7">
                        <option value="Hotel Promenade" @if($user->company == 'Hotel Promenade')  selected @endif>Hotel Promenade</option>
                        <option value="Hotel Villa Medici" @if($user->company == 'Hotel Villa Medici')  selected @endif>Hotel Villa Medici</option>
                      </select>
                      @if ($errors->has('company'))
                        <span id="company-error" class="error text-danger" for="input-company">{{ $errors->first('company') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <hr class="mx-auto mb-4" style="max-width:900px">
                <div class="row">
                  <div class="col-12 text-center">
                    <h4 class="card-title float-none font-weight-normal">Modifica password</h4>
                    <p class="card-category mt-1 float-none">
                      Inserisci la nuova password per l'utente
                    </p>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label" for="input-password">{{ __(' Password') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" input type="password" name="password" id="input-password" placeholder="{{ __('Inserisci password') }}" value="" />
                      @if ($errors->has('password'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('password') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label" for="input-password-confirmation">{{ __('Conferma Password') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group">
                      <input class="form-control" name="password_confirmation" id="input-password-confirmation" type="password" placeholder="{{ __('Conferma Password') }}" value="" />
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Modifica utente') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app', ['activePage' => 'user-management', 'title' => __('Gestione Utenti')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">{{ __('Lista utenti') }}</h4>
                            <p class="card-category"> {{ __('Qui puoi gestire gli utenti della piattaforma') }}</p>
                        </div>
                        <div class="card-body">
                            @if (session('status'))
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="alert alert-success">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <i class="material-icons">close</i>
                                            </button>
                                            <span>{{ session('status') }}</span>
                                        </div>
                                    </div>
                                </div>
                            @endif
                            <div class="row">
                                <div class="col-12 text-right">
                                    <a href="{{ route('user.create') }}"
                                       class="btn btn-sm btn-primary">{{ __('Aggiungi utente') }}</a>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead class=" text-primary">
                                    <th>
                                        {{ __('Nome') }}
                                    </th>
                                    <th>
                                        {{ __('Cognome') }}
                                    </th>
                                    <th>
                                        {{ __('Hotel') }}
                                    </th>
                                    <th class="text-right">
                                        {{ __('Azioni') }}
                                    </th>
                                    </thead>
                                    <tbody>
                                    @foreach($users as $user)
                                        <tr>
                                            <td>
                                                {{ $user->name }}
                                            </td>
                                            <td>
                                                {{ $user->surname }}
                                            </td>
                                            <td>
                                                {{ $user->company }}
                                            </td>
                                            <td class="td-actions text-right">
                                                @if ($user->id != auth()->id())
                                                        <button class="btn btn-primary btn-link" style="background: none !important; box-shadow: none!important;" href="#" data-toggle="modal" data-target="#modelId" data-ajax="#modal_content" data-method="get" data-action="{{ route('user.show', $user)}}">
                                                            <i class="material-icons">remove_red_eye</i>
                                                        </button>
                                                        <a class="btn btn-success btn-link"
                                                           href="{{ route('user.edit', $user) }}">
                                                            <i class="material-icons">edit</i>
                                                        </a>
                                                    <form action="{{ route('user.destroy', $user) }}" method="post" class="d-inline-block">
                                                        @csrf
                                                        @method('delete')
                                                        <button type="button" class="btn btn-danger btn-link"
                                                                onclick="confirm('{{ __("Sei sicuro di voler eliminare questo utente?") }}') ? this.parentElement.submit() : ''">
                                                            <i class="material-icons">close</i>
                                                        </button>
                                                    </form>
                                                @else
                                                    <button class="btn btn-primary btn-link" style="background: none !important; box-shadow: none!important;" href="#" data-toggle="modal" data-target="#modelId" data-ajax="#modal_content" data-method="get" data-action="{{ route('user.show', $user)}}">
                                                        <i class="material-icons">remove_red_eye</i>
                                                    </button>
                                                    <a class="btn btn-success btn-link"
                                                       href="{{ route('profile.edit') }}">
                                                        <i class="material-icons">edit</i>
                                                    </a>
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div id="modal_content">
                    @isset($customer)
                        @include('users.show')
                    @endisset
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/show.blade.php
<div class="modal-header">
    <div class="user mb-3">
        <div class="photo mr-3 mb-3 mb-md-0">
            <img src="@if($user->avatar == ''){{ asset('img/users/user.jpg')}}@else{{ asset('storage/images/users/'.$user->avatar)}}@endif">
        </div>
        <div class="user-info py-1">
            <h4>{{ $user->name.' '.$user->surname }}</h4>
            <small>{{$user->company}}</small>
        </div>
    </div>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body pt-0">
    <div class="row">
        <div class="col-12 info-box">
            <h4>Email</h4>
            <a href="mailto:{{$user->email}}">{{$user->email}}</a>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-primary close-btn" data-dismiss="modal">Chiudi</button>
</div>