routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

//AUTH VIEWS
Route::group(['middleware' => 'auth'], function () {

    //SEARCH ROUTES
    Route::get('coupon/search', 'CouponController@search')->name('coupon.search');
    Route::get('customers/search', 'CustomerController@search')->name('customers.search');
    Route::get('customers/search-from-home', 'CustomerController@searchFromHome')->name('customers.search-from-home');

	Route::resource('user', 'UserController');
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
	Route::post('crop-image', ['as'=>'upload-image','uses'=>'UserController@imageCrop']);
    Route::post('crop-image-coupon', ['as'=>'upload-image-coupon','uses'=>'CouponController@imageCrop']);
	Route::resource('coupon', 'CouponController');
	Route::resource('category', 'CouponCategoryController', ['except' => ['show', 'search']]);
	Route::resource('category', 'CouponCategoryController', ['except' => ['show', 'search']]);
    Route::resource('customers', 'CustomerController');
    Route::resource('operations', 'OperationController', ['except' => ['show, create, destroy']]);
    Route::resource('card', 'CardController', ['except' => ['show', 'create', 'edit']]);
    Route::resource('movement', 'MovementController', ['except' => ['show', 'create', 'edit']]);

    Route::get('customers/{customer}/cards', 'CustomerController@cards')->name('customers.cards');
    Route::put('customers/{customer}/password', 'CustomerController@password')->name('customers.password');

    //PRIZE VALIDATION
    Route::put('validate/{user}/{prize}', 'HomeController@validatePrize')->name('validate-prize');

    //FRONTEND ROUTES
    Route::get('premi/{slug}', 'FrontendController@showCoupon')->name('frontend.show-coupon');
    Route::post('{coupon}/richiesta-premio', 'FrontendController@requestPrize')->name('frontend.request-prize');
    Route::get('movimenti', 'FrontendController@allMovements')->name('frontend.movements');
    Route::get('richiesta-premio/{slug}', 'FrontendController@prizeStatus')->name('frontend.prize-status');

});

Route::get('links/{slug}', 'GuestController@showCoupon')->name('guest.show-coupon');

app/Movement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Movement extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'type', 'amount', 'location', 'partial', 'card_id', 'operation_id', 'coupon_id', 'user_id'
    ];

    /**
     * Operation - Movements relationship.
     */
    public function Operation() {
        return $this->belongsTo(Operation::class);
    }

    /**
     * Card - Movements relationship.
     */
    public function Card() {
        return $this->belongsTo(Card::class);
    }

    /**
     * User - Movements relationship.
     */
    public function User() {
        return $this->belongsTo(User::class);
    }

    /**
     * Movement - Coupon relationship.
     */
    public function Coupon() {
        return $this->belongsTo(Coupon::class);
    }

}

app/Http/Controllers/MovementController.php
<?php

namespace App\Http\Controllers;

use App\Card;
use App\Movement;
use App\Notifications\MovementNotification;
use App\Operation;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class MovementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Movement $model)
    {
        $movements = $model->paginate(15);
        return view('movements.index', compact('movements'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $operation = DB::table('operations')
            ->where('id', $request->operation_id)
            ->first();

        $amount = $request->amount * $operation->ppeuro;

        $movement = Movement::create([
            'type' => $request->type,
            'amount' => $amount,
            'location' => auth()->user()->company,
            'card_id' => $request->card_id,
            'operation_id' => $request->operation_id,
            'user_id' => auth()->user()->id
        ]);

        $card = Card::find($request->card_id);
        if($request->type == 'up'){
            $points = $card->points + $amount;
        }else {
            $points = $card->points - $amount;
        }

        $card->update([
            'points' => $points
        ]);
        $card->save();

        $customer = User::find($request->customer_id);
        $operations = Operation::all();

        $cards = $customer->cards;

        $points_to_prize = null;

        if($customer->email != null) {
            $customer->notify(new MovementNotification($movement, null, 'Nuovo movimento Fidelity | Cozzolino Hotels'));
        }

        return response()->json(['titolo'=>null, 'request' => $request, 'tipo'=>'modal','messaggio'=>'Operazione effettuata con successo!','risultato'=>view('customers.modal', ['customer' => $customer, 'cards' => $cards, 'operations' => $operations])->render()]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Movement $movement)
    {
        $card = $movement -> card;
        $movement_amount = $movement->amount;
        $card_points = $card->points;

        if($movement->type == 'up'){
            $card_points = $card_points - $movement_amount;
        }
        else {
            $card_points = $card_points + $movement_amount;
        }

        $card->update([
            'points' => $card_points
        ]);
        $card->save();

        $movement->delete();
        return redirect()->route('movement.index')->withStatus(__('Movimento eliminato con successo!'));
    }
}

resources/views/movements/index.blade.php
@extends('layouts.app', ['activePage' => 'movements-management', 'title' => __('Movimenti')])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary d-flex justify-content-between align-items-center">
                            <div class="title my-0">
                                <h4 class="card-title ">{{ __('Lista Movimenti') }}</h4>
                                <p class="card-category"> {{ __('Qui puoi visualizzare tutti i movimenti effettuati') }}</p>
                            </div>
                            {{--<div class="movements-search">
                                <input class="form-control" type="text" placeholder="Nome, cognome..." name="search" data-ajax="#movements_table" data-action="{{route('movements.search')}}" data-method="get">
                                <i class="material-icons">search</i>
                            </div>--}}
                        </div>
                        <div class="card-body">
                            @if (session('status'))
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="alert alert-success">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <i class="material-icons">close</i>
                                            </button>
                                            <span>{{ session('status') }}</span>
                                        </div>
                                    </div>
                                </div>
                            @endif
                            <div id="movements_table">
                                @include('movements.table')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/movements/table.blade.php
<div class="table-responsive">
    <table class="table">
        <thead class=" text-primary">
        <tr>
            <th>{{ __('Data') }}</th>
            <th>{{__('Cliente')}}</th>
            <th>{{ __('Tipologia') }}</th>
            <th>{{ __('Importo') }}</th>
            <th>{{__('Operatore')}}</th>
            <th>{{__('Hotel')}}</th>
            <th class="text-right">{{ __('Azioni') }}</th>
        </thead>
        <tbody>
        @forelse($movements as $movement)
            <tr>
                <td>{{\Carbon\Carbon::parse($movement->created_at)->format('d/m/Y')}}</td>
                <td>{{ $movement->card->user->name.' '.$movement->card->user->surname.' - '.$movement->card->number  }}</td>
                <td>@if($movement->partial)(PAR) @endif {{ $movement->operation->name}} @if($movement->operation->id == 5) : {{\Illuminate\Support\Str::limit($movement->coupon->title, 15, $end='...') }} @endif</td>
                <td><i
                            class="material-icons align-middle {{($movement->type === 'up') ? 'movement-up' : 'movement-down' }}">{{($movement->type === 'up') ? 'arrow_drop_up' : 'arrow_drop_down' }}</i>{{ (($movement->type === 'up') ? '+' : '-').$movement->amount }} punti
                </td>
                <td>@if($movement->operation->id == 5)Cliente @else {{ $movement->user->name.' '.$movement->user->surname }} @endif</td>
                <td>{{ $movement->location }}</td>
                <td class="td-actions text-right">
                        <form action="{{ route('movement.destroy', $movement) }}" method="post" class="d-inline-block">
                            @csrf
                            @method('delete')
                            <button type="button" class="btn btn-danger btn-link" onclick="confirm('{{ __("Sei sicuro di voler eliminare questo movimento?") }}') ? this.parentElement.submit() : ''">
                                <i class="material-icons">close</i>
                            </button>
                        </form>
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="6"><p id="no-movements" class="text-center font-weight-bold"><i
                                class="material-icons align-bottom">notification_important</i> Non è stato effettuato ancora nessun movimento</p></td>
            </tr>
        @endforelse
        </tbody>
    </table>
</div>